# Generated by Django 4.0 on 2022-01-05 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination_new', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_name', models.CharField(max_length=40)),
                ('a_location', models.CharField(max_length=40)),
                ('a_image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='new',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
    ]
