# Generated by Django 4.0 on 2022-01-06 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destination_new', '0002_airport_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airport',
            name='a_image',
        ),
    ]
